server:
  port: 8761

spring:
  application:
    name: registry-center

security:
  basic:
    enabled: true               #  开启基于HTTP basic的认证
  user:
    name: admin
    password: admin

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
